name: Playwright Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      headed:
        description: "Run Playwright in headed mode?"
        required: true
        default: false
        type: boolean

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      # ================================================================
      # 1. Checkout
      # ================================================================
      - name: Checkout code
        uses: actions/checkout@v4

      # ================================================================
      # 2. Setup Python
      # ================================================================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ================================================================
      # 3. Install dependencies
      # ================================================================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # ================================================================
      # 4. Install Playwright Chromium
      # ================================================================
      - name: Install Playwright Chromium
        run: |
          python -m playwright install --with-deps chromium

      # ================================================================
      # 5. Run HEADLESS
      # ================================================================
      - name: Run pytest - Headless
        if: ${{ github.event_name != 'workflow_dispatch' || !inputs.headed }}
        run: |
          pytest .\tests\test_01_LoginHRM.py
      #ytest -v
      #pytest .\tests\test_01_LoginHRM.py

      # ================================================================
      # 6. Run HEADED
      # ================================================================
      - name: Run pytest - Headed
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.headed }}
        run: |
          xvfb-run -a pytest -v --headed

      # ================================================================
      # 7. Upload reports
      # ================================================================
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-reports
          path: |
            reports/
            test-results/
            playwright-report/
          if-no-files-found: ignore
